[[main]]
  name = "GitHub"
  url = "https://github.com/SIGWROC/sogwroc"
  weight = 10

# [[social]]
#   name = "LinkedIn"
#   url = "https://www.linkedin.com/in/henkverlinde/"
#   weight = 20

[[social]]
  name = "Twitter"
  url = "https://twitter.com/lndgrn"
  weight = 30
