# Meta Data for SEO

## Homepage
title = "SIGWROC"
titleSeparator = "-"
titleAddition = "Writing and Rhetorics of Code"
description = "Hyas is a Hugo starter helping you build modern websites that are secure, fast, and SEO-ready — by default."

## Open Graph
images = ["logo.png"]
ogLocale = "en_US"
titleHome = "SIG on the Writing and Rhetorics of Code"

## Twitter Cards
twitterSite = "@sigwroc"
twitterCreator = "@lndgrn"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "SIGWROC"
schemaAuthor = "Chris Lindgren"
schemaAuthorTwitter = "https://twitter.com/lndgrn"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
schemaAuthorGitHub = "https://github.com/lingeringcode"
schemaLocale = "en-US"
schemaLogo = "logo.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "logo.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/lndgrn"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/sigwroc"

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "320"

# Footer
footer = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://gethyas.com/\">Hyas</a>"

# Feed
copyRight = "Copyright (c) 2020-2021 Henk Verlinde"

# Alert
alert = true
alertDismissable = true
alertText = "Deliver web projects 10x faster. <a class=\"alert-link\" href=\"https://www.netlify.com/whitepaper/\" target=\"_blank\" rel=\"noopener\">Get the free enterprise paper →</a>"
