[build]
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "16.13.1"
  NPM_VERSION = "8.1.2"

[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build -- -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "npm run build -- -b $DEPLOY_PRIME_URL"

[context.next]
  command = "npm run build"

[context.next.environment]
  HUGO_ENV = "next"

[dev]
  framework = "#custom"
  command = "npm run start"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false

[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "default-src 'self' 'unsafe-inline' https://www.google-analytics.com;img-src 'self' 'unsafe-inline' https://www.google.com; media-src 'self' https://www.youtube.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com connect.facebook.net https://www.google-analytics.com; script-src-elem 'self' 'unsafe-inline' 'unsafe-eval' https://www.google-analytics.com; frame-src 'self' https://app.frame.io https://www.youtube.com/ https://vimeo.com; X-Frame-Options: SAMEORIGIN"